### ISSUE TITLE
HTML comments inside the title

### ISSUE THREAD

**Issue by oskarrough** [paddle8/ember-document-title#10]
Hi, I'm having some trouble since this addon generates empty HTML comments inside the `<title>` tag which unfortunately shows up in Google.

```HTML
<title><!---->My post title | <!---->Blog | <!---->Site title<!----></title>
```

In app.hbs I have:

```handlebars
{{document-title seperator=" — " prepend="true" title="Kunstjagd"}}
```

in blog.hbs:

```handlebars
{{document-title title="Blog"}}
```

and finally in blog/post.hbs:

```handlebars
{{document-title title=model.title}}
```

Any ideas?

**Comment by tim-evans** [comment]
Hmm.... This is unfortunate. Ping @chrislopresto

**Comment by tim-evans** [comment]
Also, I believe at some point htmlbars switched internally from using text nodes as boundary markers to comment nodes.

**Comment by oskarrough** [comment]
For whatever it's worth, those empty comments actually make the site stand out in the search results. Client didn't agree.

**Comment by tim-evans** [comment]
Haha. Well, that's something :P

**Comment by tim-evans** [comment]
@rwjblue Is there anything I can do about this?

**Comment by tim-evans** [comment]
This will no longer be an issue when 1.13.0 is released.

**Comment by oskarrough** [comment]
Great, thanks!
