### ISSUE TITLE
Push tags to repo?

### ISSUE THREAD

**Issue by rwjblue** [paddle8/ember-document-title#14]
Makes it much easier to do compare views across release versions...

**Comment by tim-evans** [comment]
@rwjblue Thanks for the reminder :)

**Comment by rwjblue** [comment]
As a slight aside, I **love** [ember-cli-release](https://github.com/lytics/ember-cli-release) for managing these things.  Basically, `ember release && npm publish` will:

* Bump package.json and bower.json (patch version by default but configurable via `ember release --major` etc)
* Tag
* Push tag and commit

**Comment by tim-evans** [comment]
Ooh. Yes. I think I'll merge this in to my other addons.
