### ISSUE TITLE
npm version 1.13.0 on ember-cli@0.2.7/Ember1.12 has some issues

### ISSUE THREAD

**Issue by xomaczar** [paddle8/ember-document-title#15]
1. HTMLBar-AST throws error during build
2. W/o AST {{title}} helper is not found

**Comment by tim-evans** [comment]
@xomaczar 1.13.0 does not work for < 1.13. Please use https://github.com/paddle8/ember-document-title/releases/tag/1.1.11 for any release below 1.12

I'll document this in the README for those upgrading from previous versions. Thanks!
