### ISSUE TITLE
Component - Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by thanosexcite** [paddle8/ember-document-title#16]
Hi there. I'm getting this error when visiting routes that have a google-map component (from ember-google-map):

```
Uncaught TypeError: Cannot read property 'match' of undefined
```

```
ember-resolver.js line 192
podBasedComponentsInSubdir(
...
  if (parsedName.type === 'component' || parsedName.fullNameWithoutType.match(/^components/)) {...}
...
}
```

If I remove the ember-document-title dependency from package.js, those routes work again.

Not sure if this is an issue with the component or ember-document-title. If I can do something to help investigate it, please tell me. Your addon is awesome btw and I think it should be something that comes with ember by default.

Thanks

**Comment by tim-evans** [comment]
What version of this addon / ember are you using?

**Comment by thanosexcite** [comment]
The versions I'm using are:

"ember": "1.13.5"
"ember-cli": "1.13.1"
"ember-document-title": "2.0.0"
"ember-google-map": "0.0.22"

Thanks

**Comment by tim-evans** [comment]
Hmm. I think you skipped the 1.13 release of ember-document-title, there's a bunch of deprecations in that one. The syntax changed a lot between the two releases. Could you try that release and lemme know how that goes?

**Comment by thanosexcite** [comment]
I'm using the addon on a new project, so I don't have any old code to migrate. But maybe I'm using some invalid syntax. Will check again. Thanks.
