### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by bierdybard** [paddle8/ember-document-title#19]
This appears to be the same issue as brought up in #16, except I am matching the ember-document-title version (1.13.1) to the Ember version (1.13.5).

Versions:

Ember: 1.13.5
Ember Data: 1.13.7
ember-document-title: 1.13.1

The breakpoint points to this line in Ember.DefaultResolver definition:
```javascript
    podBasedComponentsInSubdir: function(parsedName) {
      var podPrefix = this.namespace.podModulePrefix || this.namespace.modulePrefix;
      podPrefix = podPrefix + '/components';

      if (parsedName.type === 'component' || parsedName.fullNameWithoutType.match(/^components/)) { //<-- this line
        return this.podBasedLookupWithPrefix(podPrefix, parsedName);
      }
    },
```
Unfortunately, I'm not having luck getting a full traceback so I can see where this is being called from.

The particular usage that seems to be failing here is rendering into an existing view--in particular, a modal display. When creating the modal I'm following the same basic procedure as outlined in the cookbook in Ember Guides; i.e. programmatically rendering into an outlet: http://guides.emberjs.com/v1.12.0/cookbook/user_interface_and_interaction/using_modal_dialogs/ . The end result is that the modal component is not loaded/rendered.

Installing and including the addon causes this behavior without any further change; removing it restores the functionality of the modal.

Let me know if I can help with any more information.

**Comment by tim-evans** [comment]
That's pretty weird. My intuition says that this is being caused by the interaction of the `{{title}}` helper in conjunction with the modal, but I'm not sure. Could you create a ember twiddle based off of this? http://ember-twiddle.com/95fd601c9b4c2ed3ad68

**Comment by bierdybard** [comment]
This quick mock duplicates the issue:
http://ember-twiddle.com/286983fb614909031047

**Comment by tim-evans** [comment]
Apparently the `{{title}}` helper collides with the implicit `{{title}}` you've declared on https://gist.github.com/bierdybard/286983fb614909031047#file-templates-components-ui-modal-hbs-L3. Changing that line to `{{model.title}}` fixes the issue. Maybe poking someone from the core team about this would be helpful.

**Comment by bierdybard** [comment]
That did the trick. {{title}} came from a property on the ui-modal component; I changed that to {{header}} in my app and all seems to be well. Yay global namespaces :)

**Comment by bierdybard** [comment]
I do wonder if #16 was caused by the same.

**Comment by tim-evans** [comment]
That sounds correct. Hey @rwjblue, is there any way for helpers not to collide with values?
