### ISSUE TITLE
Collisions when rendering a property named `title` in templates

### ISSUE THREAD

**Issue by tim-evans** [paddle8/ember-document-title#20]
With this helper, rendering something named `title` will break the app, resulting in a very hard to track down stack trace.

```handlebars
{{title}}
```

Technically, this addon should work when invoked like so:

```handlebars
{{title title}}
```

Where the first title is the helper and the second title is the property in scope of the template. This likely needs help from the ember core team.

**Comment by brandonarbini** [comment]
In the meantime, it'd be nice to rename the helper from `title` to `pageTitle`. Less likely to have a collision, but the core issue should still be addressed.

**Comment by tim-evans** [comment]
@brandonarbini Working on this with people. This should be addressed soon :)

**Comment by brandonarbini** [comment]
Super cool. I'm really new to Ember, so I'd offer to help if I knew what I was doing. Thanks!

**Comment by tim-evans** [comment]
Resolved with https://github.com/ember-cli/ember-resolver/pull/105. Use ember-resolver master if necessary.

**Comment by tim-evans** [comment]
@brandonarbini Looks like I'll have to change the helper. *again* Sigh. `{{page-title}}` might be the winner

**Comment by tim-evans** [comment]
Fixed by https://github.com/paddle8/ember-document-title/commit/669ea8021eeb6057c0acdedd908335b784da3011

**Comment by brandonarbini** [comment]
Killer. Thanks!
