### ISSUE TITLE
Path or pattern "(generated ember-document-title addon)/**/*.js" did not match any files

### ISSUE THREAD

**Issue by caseyjenks** [paddle8/ember-document-title#4]
Installed addon, and build is failing. Any ideas?

Build failed.
Path or pattern "(generated ember-document-title addon)/**/*.js" did not match any files
Error: Path or pattern "(generated ember-document-title addon)/**/*.js" did not match any files

**Comment by tim-evans** [comment]
I think this requires ember-cli 0.2.0-beta.1

**Comment by tim-evans** [comment]
@caseyjenks what version of ember are you using?

**Comment by caseyjenks** [comment]
@tim-evans 1.10.0

**Comment by tim-evans** [comment]
Hmmm. That should work. I'm currently trying to figure this out.

**Comment by caseyjenks** [comment]
going to try upgrading my version of ember CLI

**Comment by caseyjenks** [comment]
Upgraded to 0.1.15, and got a little bit further. The this time is:

Uncaught Error: Could not find module ember-document-title/addon/components/document-title        loader.js:58

**Comment by tim-evans** [comment]
Yep, I'm there as well. Weird.

**Comment by tim-evans** [comment]
@stefanpenner I'm seeing `(generated ember-document-title addon)` under `require._eak_seen`. I've never had this problem before with addons. Any ideas?

**Comment by tim-evans** [comment]
When installing this addon, host applications have the following code in vendor.js:

```javascript
define("(generated ember-document-title addon)", ["(generated ember-document-title addon)/index","exports"], function(__index__, __exports__) {
  "use strict";
  Object.keys(__index__).forEach(function(key){
    __exports__[key] = __index__[key];
  });
});
```

**Comment by stefanpenner** [comment]
what the shit lol

**Comment by stefanpenner** [comment]
the offending code doesn't appear in master.

**Comment by tim-evans** [comment]
wut.

any ideas on what I should do?

**Comment by stefanpenner** [comment]
[v0.2.0-beta.1](https://github.com/ember-cli/ember-cli/blob/v0.2.0-beta.1/lib/models/addon.js#L648)
[master](https://github.com/ember-cli/ember-cli/blob/master/lib/models/addon.js#L642)

**Comment by stefanpenner** [comment]
@tim-evans I am just about to test master, if that works i'll cut a new ember-cli.

**Comment by tim-evans** [comment]
Yay :heart:

**Comment by tim-evans** [comment]
This is fixed with the most recent deploy. Phew!

**Comment by caseyjenks** [comment]
Awesome, confirmed on my end as well!
