### ISSUE TITLE
Excess separator is added when replace=true

### ISSUE THREAD

**Issue by buschtoens** [paddle8/ember-document-title#6]
First of all, thanks for this brilliant addon! This is *just* what I was looking for and implementing the title in the template is very elegant in my opinion.

---

Now onto the problem. It seems like `replace=true` does not "remove" the parent separator.

Consider these templates:

```hbs
// application.hbs

{{#document-title prepend=true separator=" ★ "}}Hollywood{{/document-title}}
```

```hbs
// index.hbs

{{#document-title replace=true}}Hollywood ★ Stars everywhere{{/document-title}}
```

```hbs
// blog.hbs

{{#document-title}}Blog{{/document-title}}
```

- Expected title for `/blog`: `Blog ★ Hollywood`  
works alright
- Expected title for `/`: `Hollywood ★ Stars everywhere`  
Actual title: `Hollywood ★ Stars everywhere ★ `  
Note the trailing `★`.

A hotfix is to set `separator=""` in the child templates that replace the parent title.

**Comment by buschtoens** [comment]
This only happens when `prepend=true` is used.

**Comment by buschtoens** [comment]
From a quick glance at the code, this seems to be the problem:

```js
  render: function (buffer) {
    var titleTag = document.getElementsByTagName('title')[0];
    var previous = get(this, 'previous');
    var replace = get(this, 'replace');
    if (previous && get(previous, 'prepend')) {
      if (get(previous, 'showSeparatorBefore')) {
        var pivot = get(previous, 'previous');
        if (pivot) {
          set(pivot, 'showSeparatorAfter', true);      // !replace here?
        }
        set(previous, 'showSeparatorBefore', false);
      }
      set(this, 'showSeparatorAfter', true);           // !replace here?
      this._morph = buffer.dom.insertMorphBefore(titleTag, previous._morph.start);
    } else {
      set(this, 'showSeparatorBefore', !replace);
      this._morph = buffer.dom.appendMorph(titleTag);
    }
    this._super.apply(this, arguments);
  },
```

[document-title.js:43](https://github.com/paddle8/ember-document-title/blob/master/addon/components/document-title.js#L43) and [document-title.js:47](https://github.com/paddle8/ember-document-title/blob/master/addon/components/document-title.js#L47).

At least this fixed it for me. But I don't know, if I have introduced other bugs with this.

**Comment by tim-evans** [comment]
I'll add a test and fix this when I get into work tomorrow. Thanks for the issue, and for the wonderful feedback :)

**Comment by buschtoens** [comment]
:+1:

**Comment by tim-evans** [comment]
Update to 1.1.9 and it should be fixed. And yup, your solution fixed it :)

**Comment by buschtoens** [comment]
Awesome! Works like a charm. Always happy to be of any help. :)
