### ISSUE TITLE
Glimmer release

### ISSUE THREAD

**Issue by chrism** [paddle8/ember-document-title#9]
Hi,

I'm just in the process of trying to update to Glimmer & was wondering if you are planning to publish a new version to npm soon or whether I should start by using this github repo for now.

Thanks.

**Comment by tim-evans** [comment]
@chrism This is a difficult addon to update, since it uses some private APIs. I believe @chrislopresto is taking a look at it :)

**Comment by chrism** [comment]
@tim-evans ok, thanks for letting me know :)

**Comment by chrislopresto** [comment]
@tim-evans This branch of ember-wormhole https://github.com/yapplabs/ember-wormhole/tree/range-safely (along with a small hack working around a glimmer bug) should unblock development on glimmer-compatible wormhole-based versions of document-title and favicon components.

**Comment by tim-evans** [comment]
@chrislopresto I have a wip branch here: https://github.com/paddle8/ember-document-title/tree/using-wormhole

The most interesting bug so far is that `didInsertElement` isn't called in hierarchical order, which causes a bunch of test failures. I'm not sure why it does that, and I'm not sure whether it's a bug or not- when the `render` hooks were called, the order was determinable.

Other than that, I'm trying to do prepends, which I've written a copy of `appendRange`.

The last detail is that I cannot write this addon as a tagless view. If that's not possible, I think that's an ok compromise for stability.

**Comment by tim-evans** [comment]
Since 1.13 is released, and 2.0 is coming up soon, I think I'm going to try to tackle this at an Ember project night. I'm going to also change the semver so this addon will skip 1.0 and go straight to 2.0 to make it follow http://emberjs.com/blog/2015/06/16/ember-project-at-2-0.html

**Comment by knownasilya** [comment]
@tim-evans nice! looking forward to it.

**Comment by knownasilya** [comment]
@rwjblue do you have any thoughts regarding the APIs used here?

**Comment by tim-evans** [comment]
There's some changes on master that will be the solution for 1.13.0. The work now is documenting and providing htmlbars AST transformations to support this.

**Comment by knownasilya** [comment]
@tim-evans so master should work with 1.13?

**Comment by tim-evans** [comment]
Yessir! I removed the need to depend on ember-wormhole.

**Comment by caseyjenks** [comment]
I'm getting Uncaught TypeError: Cannot read property 'appendMorph' of undefined"

line 53 of document-title.js: this._morph = buffer.dom.appendMorph(titleTag);

Any ideas?

**Comment by tim-evans** [comment]
@caseyjenks It's not actually released yet. You can use the package by referencing git, but there's still some work to be done. That's why this ticket isn't closed.

**Comment by tim-evans** [comment]
Released 1.13.0.

Deprecation warnings should show up in your console with old style of rendering the title. Open any issues if you have trouble. :tada:

**Comment by knownasilya** [comment]
:rocket: yay!

**Comment by caseyjenks** [comment]
nice work!

**Comment by rwjblue** [comment]
@tim-evans - Thank you for your hard work on this!
